FROM madnificent/ember:3.28.5 as builder

LABEL maintainer="info@redpencil.io"

WORKDIR /app
COPY package.json .
RUN npm install --legacy-peer-deps

COPY . .
RUN ember build --environment production

FROM redpencil/fastboot-app-server:1.1.0

COPY --from=builder /app/dist /app
